#
# 基于 https://github.com/P3TERX/Actions-OpenWrt
#
# 文件: .github/workflows/immortalwrt-builder.yml
# 描述: 使用 GitHub Actions 构建 ImmortalWrt 固件
#

# 工作流名称
name: ImmortalWrt Builder

# 触发条件
on:
  repository_dispatch:  # 允许通过 API 触发工作流
  workflow_dispatch:    # 允许手动在 GitHub 界面触发工作流

# 环境变量设置
env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt  # ImmortalWrt 源代码仓库地址
  REPO_BRANCH: master  # 使用的分支
  FEEDS_CONF: feeds.conf.default  # feeds 配置文件
  CONFIG_FILE: .config  # 编译配置文件
  DIY_P1_SH: diy-part1.sh  # 自定义脚本（在更新 feeds 前运行）
  DIY_P2_SH: diy-part2.sh  # 自定义脚本（在更新 feeds 后运行）
  UPLOAD_BIN_DIR: false  # 是否上传整个 bin 目录
  UPLOAD_FIRMWARE: true  # 是否上传固件
  UPLOAD_RELEASE: true  # 是否创建发布版本
  TZ: Asia/Shanghai  # 时区设置

# 任务定义
jobs:
  build:
    runs-on: ubuntu-22.04  # 在 Ubuntu 22.04 环境运行

    steps:
    # 检出代码
    - name: Checkout
      uses: actions/checkout@main

    # 初始化环境
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive  # 禁用交互式前端
      run: |
        # 清理不需要的文件和目录，释放空间
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        # 更新 apt 并安装编译 ImmortalWrt 所需的依赖包
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd
        # 清理 apt 缓存
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        # 设置时区
        sudo timedatectl set-timezone "$TZ"
        # 创建工作目录
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    # 克隆 ImmortalWrt 源代码
    - name: Clone source code
      working-directory: /workdir
      run: |
        # 显示磁盘使用情况
        df -hT $PWD
        # 克隆 ImmortalWrt 源码
        git clone $REPO_URL -b $REPO_BRANCH immortalwrt
        # 创建软链接到工作区
        ln -sf /workdir/immortalwrt $GITHUB_WORKSPACE/immortalwrt

    # 加载自定义 feeds 配置
    - name: Load custom feeds
      run: |
        # 如果存在自定义 feeds 配置，则替换默认配置
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF immortalwrt/feeds.conf.default
        # 赋予自定义脚本执行权限
        chmod +x $DIY_P1_SH
        cd immortalwrt
        # 执行第一个自定义脚本（在更新 feeds 前）
        $GITHUB_WORKSPACE/$DIY_P1_SH

    # 更新 feeds（软件包源）
    - name: Update feeds
      run: cd immortalwrt && ./scripts/feeds update -a

    # 安装 feeds 中的所有软件包
    - name: Install feeds
      run: cd immortalwrt && ./scripts/feeds install -a

    # 加载自定义配置
    - name: Load custom configuration
      run: |
        # 如果存在自定义文件，则移动到 immortalwrt/files 目录
        [ -e files ] && mv files immortalwrt/files
        # 如果存在配置文件，则移动到 immortalwrt/.config
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE immortalwrt/.config
        # 赋予第二个自定义脚本执行权限
        chmod +x $DIY_P2_SH
        cd immortalwrt
        # 执行第二个自定义脚本（在更新 feeds 后）
        $GITHUB_WORKSPACE/$DIY_P2_SH

    # 下载编译所需的软件包
    - name: Download package
      id: package
      run: |
        cd immortalwrt
        # 生成默认配置
        make defconfig
        # 下载所需的软件包，使用 8 线程
        make download -j8
        # 查找并显示小于 1024 字节的下载文件（可能是下载失败的文件）
        find dl -size -1024c -exec ls -l {} \;
        # 删除小于 1024 字节的文件
        find dl -size -1024c -exec rm -f {} \;

    # 编译固件
    - name: Compile the firmware
      id: compile
      run: |
        cd immortalwrt
        # 显示使用的线程数
        echo -e "$(nproc) thread compile"
        # 尝试使用多线程编译，如果失败则尝试单线程，再失败则使用单线程并显示详细信息
        make -j$(nproc) || make -j1 || make -j1 V=s
        # 设置编译成功状态
        echo "status=success" >> $GITHUB_OUTPUT
        # 提取设备名称
        grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
        # 如果有设备名称，则添加到环境变量
        [ -s DEVICE_NAME ] && echo "DEVICE_NAME=_$(cat DEVICE_NAME)" >> $GITHUB_ENV
        # 添加日期时间到环境变量
        echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    # 检查空间使用情况
    - name: Check space usage
      if: (!cancelled())
      run: df -hT

    # 上传 bin 目录（如果设置了 UPLOAD_BIN_DIR）
    - name: Upload bin directory
      uses: actions/upload-artifact@main
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
      with:
        name: ImmortalWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: immortalwrt/bin

    # 整理文件（删除不需要的 packages 目录）
    - name: Organize files
      id: organize
      if: env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd immortalwrt/bin/targets/*/*
        rm -rf packages
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    # 上传固件目录
    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: ImmortalWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    # 生成发布标签（如果设置了 UPLOAD_RELEASE）
    - name: Generate release tag
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      run: |
        # 使用日期时间作为发布标签
        echo "release_tag=$(date +"%Y.%m.%d-%H%M")" >> $GITHUB_OUTPUT
        # 创建发布说明文件
        touch release.txt
        echo "status=success" >> $GITHUB_OUTPUT

    # 将固件上传到 GitHub Releases
    - name: Upload firmware to release
      uses: softprops/action-gh-release@master
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*

    # 删除旧的工作流运行记录
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0  # 不保留任何天数
        keep_minimum_runs: 2  # 至少保留 2 次运行记录

    # 删除旧的发布版本
    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@master
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 3  # 保留最新的 3 个版本
        delete_tags: true  # 同时删除标签
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
